/* AUTO-GENERATED by tools/port-to-cloudflare.cjs — do not edit by hand.
   Edit netlify/functions/ and re-run the script.

   Workers KV shim presenting the same tiny surface as Netlify Blobs, so the
   business logic below is byte-identical across both platforms. */
function makeStore(env, binding) {
  const kv = env[binding];
  if (!kv) throw new Error('KV namespace ' + binding + ' is not bound');
  return {
    async get(key, opts) {
      const raw = await kv.get(key);
      if (raw === null || raw === undefined) return null;
      if (opts && opts.type === 'json') {
        try { return JSON.parse(raw); } catch (e) { return null; }
      }
      return raw;
    },
    async setJSON(key, val) { await kv.put(key, JSON.stringify(val)); }
  };
}

/* =============================================================================
   /api/messages — shared inbox
   -----------------------------------------------------------------------------
   Before this existed, an enquiry submitted on a customer's phone was written
   to THAT phone's localStorage. The admin never saw it. Orders had the same
   problem. This gives every message one shared home the staff portal can read
   from any device.

   Endpoints
     POST /api/messages          public  log a message (enquiry, order, etc.)
     GET  /api/messages          staff   read the inbox
     POST /api/messages  {action:'read'|'delete'|'read-all'}   staff
   ========================================================================== */


const KEY = 'messages-v1';
const LIMIT = 1000;

const json = (body, status = 200) => new Response(JSON.stringify(body), {
  status,
  headers: {
    'content-type': 'application/json',
    'cache-control': 'no-store',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'content-type, x-admin-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS'
  }
});

const clean = (v, max) => String(v ?? '').replace(/[<>]/g, '').trim().slice(0, max);
let _env = null;
const store = () => makeStore(_env, 'LARA_MESSAGES');

/* ---------------------------------------------------------------------------
   Outbound notification.

   Previously a new order was only written to storage, so unless the owner
   happened to open the admin they never learned a sale had happened. Sending
   from the server means it works even if the buyer closes the tab immediately,
   which the old browser-side send did not.

   Configure ONE of these in your host's environment variables:
     RESEND_KEY  + NOTIFY_EMAIL     (resend.com, 3,000 emails/month free)
     BREVO_KEY   + NOTIFY_EMAIL     (brevo.com, 300/day free)
   With neither set, messages are still stored — you just are not pinged.
   Never throws: a notification failure must not fail the customer's order.
------------------------------------------------------------------------- */
async function notify(entry) {
  const to = (_env && _env.NOTIFY_EMAIL);
  if (!to) return 'no-recipient';

  const subject = entry.type === 'order'
    ? `New order — ${entry.subject || entry.name}`
    : `${entry.type === 'enquiry' ? 'Enquiry' : 'Website'} from ${entry.name || 'a visitor'}`;

  const lines = [
    entry.name ? `From: ${entry.name}` : '',
    entry.email ? `Email: ${entry.email}` : '',
    entry.phone ? `Phone: ${entry.phone}` : '',
    '',
    entry.body || '',
    '',
    '— sent automatically by your website'
  ].filter(Boolean).join('\n');

  try {
    if ((_env && _env.RESEND_KEY)) {
      const r = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          authorization: `Bearer ${(_env && _env.RESEND_KEY)}`
        },
        body: JSON.stringify({
          /* Resend's shared sandbox sender is EXACTLY 'onboarding@resend.dev'.
             Any other @resend.dev address is rejected, so a wrong default here
             means order emails fail silently until a domain is verified.
             Set NOTIFY_FROM to orders@larabeautyatelier.com once the domain is
             verified at resend.com/domains. */
          from: (_env && _env.NOTIFY_FROM) || 'Lara Beauty Atelier <onboarding@resend.dev>',
          to: [to],
          subject,
          text: lines,
          reply_to: entry.email || undefined
        })
      });
      if (!r.ok) {
        /* Log the provider's reason. Without this a rejected sender address or
           an unverified domain looks identical to "no email configured", and
           you find out by never receiving an order. */
        const why = await r.text().catch(() => '');
        console.error('Resend rejected the email:', r.status, why.slice(0, 400));
      }
      return r.ok ? 'resend' : `resend-failed-${r.status}`;
    }

    if ((_env && _env.BREVO_KEY)) {
      const r = await fetch('https://api.brevo.com/v3/smtp/email', {
        method: 'POST',
        headers: { 'content-type': 'application/json', 'api-key': (_env && _env.BREVO_KEY) },
        body: JSON.stringify({
          sender: { email: (_env && _env.NOTIFY_FROM) || to, name: 'Lara Beauty Atelier' },
          to: [{ email: to }],
          subject,
          textContent: lines,
          ...(entry.email ? { replyTo: { email: entry.email } } : {})
        })
      });
      return r.ok ? 'brevo' : `brevo-failed-${r.status}`;
    }
  } catch (err) {
    return 'notify-error';
  }
  return 'stored-only';
}

const isStaff = req => {
  const expected = (_env && _env.ADMIN_TOKEN);
  return !!expected && req.headers.get('x-admin-token') === expected;
};

async function readAll() {
  const data = await store().get(KEY, { type: 'json' });
  return Array.isArray(data) ? data : [];
}

async function handle(req) {
  if (req.method === 'OPTIONS') return json({});

  if (req.method === 'GET') {
    if (!isStaff(req)) return json({ error: 'unauthorised' }, 401);
    return json({ messages: await readAll() });
  }

  if (req.method !== 'POST') return json({ error: 'method not allowed' }, 405);

  let payload;
  try { payload = await req.json(); }
  catch { return json({ error: 'bad json' }, 400); }

  const list = await readAll();

  /* Staff maintenance actions --------------------------------------------- */
  if (payload.action) {
    if (!isStaff(req)) return json({ error: 'unauthorised' }, 401);

    if (payload.action === 'read') {
      const m = list.find(x => x.id === payload.id);
      if (m) m.read = payload.read !== false;
    } else if (payload.action === 'read-all') {
      list.forEach(m => { m.read = true; });
    } else if (payload.action === 'delete') {
      const i = list.findIndex(x => x.id === payload.id);
      if (i >= 0) list.splice(i, 1);
    } else {
      return json({ error: 'unknown action' }, 400);
    }

    await store().setJSON(KEY, list);
    return json({ ok: true });
  }

  /* Public: log a new message ---------------------------------------------
     Same reasoning as reviews: the contact form is an open endpoint, so cap
     how often one connection can post to it. */
  const ip = req.headers.get('cf-connecting-ip')
    || req.headers.get('x-forwarded-for') || 'unknown';
  const rlKey = 'ratelimit';
  const rl = (await store().get(rlKey, { type: 'json' })) || {};
  const now = Date.now();
  const WINDOW = 60 * 60 * 1000, MAX = 10;
  for (const [k, times] of Object.entries(rl)) {
    const kept = times.filter(t => now - t < WINDOW);
    if (kept.length) rl[k] = kept; else delete rl[k];
  }
  if ((rl[ip] || []).length >= MAX) {
    return json({ error: 'Too many messages from this connection. Try again later.' }, 429);
  }
  rl[ip] = [...(rl[ip] || []), now];
  await store().setJSON(rlKey, rl);

  const entry = {
    id: 'MSG-' + Date.now().toString(36).toUpperCase(),
    date: new Date().toISOString(),
    read: false,
    delivered: !!payload.delivered,
    type: clean(payload.type, 20) || 'enquiry',
    subject: clean(payload.subject, 200),
    name: clean(payload.name, 100),
    email: clean(payload.email, 160),
    phone: clean(payload.phone, 40),
    body: clean(payload.body, 5000),
    meta: payload.meta && typeof payload.meta === 'object' ? payload.meta : null
  };

  /* Orders and enquiries are worth an email; subscriber pings are not. */
  if (entry.type === 'order' || entry.type === 'enquiry') {
    const via = await notify(entry);
    entry.delivered = via === 'resend' || via === 'brevo';
    entry.via = via;
  }

  list.unshift(entry);
  await store().setJSON(KEY, list.slice(0, LIMIT));
  return json({ ok: true, id: entry.id, notified: entry.delivered === true });
};

/* Cloudflare Pages Functions entry point. File location determines the route:
   functions/api/messages.js  ->  /api/messages */
export async function onRequest(context) {
  _env = context.env;
  return handle(context.request);
}
